AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: Patent Text Analysis Pipeline serverless stack to mining patent pdf documents. 
  The pipeline will be triggered when a document is added to the s3 bucket that is being watched by the ProcessPatentDocuments function.

Parameters:
  Tag:
    Type: String
    Default: latest
    Description: Docker tag to build and deploy.
  LOCAL_ENV:
    Type: Boolean
    Default: false
    Description: Run local env.

Resources:
  TaRepo: # the ECR repo name
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "ta-repository"
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - "arn:aws:iam::${AWS::Region}:${AWS::AccountId}:user/*"
            Action: 
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"