name: CI

on: [ push , pull_request , workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make init
      - name: Lint code
        run: make lint
      - name: Build Container
        run: make build
      - name: Unit Tests
        run: make test
      - name: Integration Tests
        run: make run-local

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make init

      - name: SAM build
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "build"
      
      - name: SAM Deploy
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "deploy"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
