name: CI

on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make init

      - name: Lint code
        run: make lint
        
      - name: Test 
        run: make test

      # Runs a single command using the runners shell
      - name: Run sam build
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "build"