name: CI Workflow

on:
  push:
      branches: 
        - '*'
  pull_request:
      types: [closed, opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make init
      - name: Lint code
        run: make lint
      - name: Unit Tests
        run: pytest -v -s ./src/process_documents/tests/test_process_documents.py
      
      # The integration tests are commented-out because installing the
      # local aws stack takes a long time and burns through our CI quota
      # - name: SAM build
      #   uses: youyo/aws-sam-action/python3.8@v2
      #   with:
      #     sam_command: "build"
      # - name: Start Local Stack
      #   working-directory: ${{ github.workspace }}
      #   run: make stack-up
      # - name: Integration Tests
      #   working-directory: ${{ github.workspace }}
      #   run: make run-ci

  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    needs: build
    environment: AWS_US_EAST_1_1
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: make init
      - name: Configure AWS credentials
        id: credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Cloudformation deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ta-stack
          template: stack-template.yaml
          no-fail-on-empty-changeset: "1"
      - name: SAM build package and deploy
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "build --cached --parallel"
      - name: SAM package
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "package --output-template-file packaged-template.yaml --debug --region us-east-1 --image-repository 147427553671.dkr.ecr.us-east-1.amazonaws.com/ta-repository --s3-bucket ta-stack-bucket" 
      - name: SAM deploy
        uses: youyo/aws-sam-action/python3.8@v2
        with:
          sam_command: "deploy -t packaged-template.yaml --stack-name ta-serverless-stack --region us-east-1 --debug --image-repository 147427553671.dkr.ecr.us-east-1.amazonaws.com/ta-repository --s3-bucket ta-stack-bucket --capabilities CAPABILITY_IAM  --no-fail-on-empty-changeset"
          actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
