name: CI

on:
  - push
  - pull_request  
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make init

      - name: Lint code
        run: make lint
        
      - name: Test 
        run: make test

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  sam-build:
    runs-on: ubuntu-20.04
    container: aws-sam-cli-build-image-python3.8
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: make init
      
      - name: Test 
        run: make test

      - name : Build SAM Stack
        run: make build-stack
      