name: Git Push Workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main
# PSV-6 Adding the deployment pipeline
jobs:
  build:
    runs-on: ubuntu-latest
    container: amazon/aws-sam-cli-build-image-python3.8:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Python
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Update Python
      run: |
        python -m pip install --upgrade pip

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements_local.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Build Stack
      run: |
        make build-stack

    - name: Run unit tests
      run: |
        make test